version: '3.8'

services:
  backend-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-backend-prod
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - reverse-proxy-net

networks:
  reverse-proxy-net:
    external: true