version: '3.8'

services:
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-backend-dev
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - reverse-proxy-net

networks:
  reverse-proxy-net:
    external: true