# Datenbank (Lokal)
spring.datasource.url=jdbc:postgresql://localhost:5432/timetracker
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (Lokal: update ist okay)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Security Test User
spring.security.user.name=admin
spring.security.user.password=admin123

# JWT Secret (Nur für Dev!)
app.jwt.secret=AkYoumSmE9nr2o2ruqlOnL2Gn/938QH5sxo7sG62CXw=

# CORS: Erlaube Anfragen vom Vite Dev-Server
app.cors.allowed-origins=http://localhost:5173

# Logging (Ausführlich für Debugging)
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG