spring.application.name=time
spring.datasource.url=jdbc:postgresql://localhost:5432/timetracker
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.security.user.name=admin
spring.security.user.password=admin123


app.jwt.secret: AkYoumSmE9nr2o2ruqlOnL2Gn/938QH5sxo7sG62CXw=
app.jwt.expiration-ms: 864000000

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
